INSERT INTO menu (name, cooking_time_sec) VALUES ("Spaghetti", 300);
INSERT INTO menu (name, cooking_time_sec) VALUES ("Pizza", 600);
INSERT INTO menu (name, cooking_time_sec) VALUES ("Hamburger", 300);
INSERT INTO menu (name, cooking_time_sec) VALUES ("Salad", 180);
INSERT INTO menu (name, cooking_time_sec) VALUES ("Fries", 600);
INSERT INTO menu (name, cooking_time_sec) VALUES ("Onion Rings", 360);
INSERT INTO menu (name, cooking_time_sec) VALUES ("Milk Shake", 240);
INSERT INTO menu (name, cooking_time_sec) VALUES ("Sundae", 120);
INSERT INTO menu (name, cooking_time_sec) VALUES ("Apple Pie", 60);
INSERT INTO menu (name, cooking_time_sec) VALUES ("Soda", 60);


INSERT INTO tables (name, capacity) VALUES ("A", 2);
INSERT INTO tables (name, capacity) VALUES ("B", 2);
INSERT INTO tables (name, capacity) VALUES ("C", 2);
INSERT INTO tables (name, capacity) VALUES ("D", 2);
INSERT INTO tables (name, capacity) VALUES ("E", 4);
INSERT INTO tables (name, capacity) VALUES ("F", 4);
INSERT INTO tables (name, capacity) VALUES ("G", 4);
INSERT INTO tables (name, capacity) VALUES ("H", 4);
INSERT INTO tables (name, capacity) VALUES ("I", 6);
INSERT INTO tables (name, capacity) VALUES ("J", 6);
INSERT INTO tables (name, capacity) VALUES ("K", 6);
INSERT INTO tables (name, capacity) VALUES ("L", 6);
INSERT INTO tables (name, capacity) VALUES ("M", 8);
INSERT INTO tables (name, capacity) VALUES ("N", 8);
INSERT INTO tables (name, capacity) VALUES ("O", 8);
INSERT INTO tables (name, capacity) VALUES ("P", 8);
INSERT INTO tables (name, capacity) VALUES ("Q", 10);
INSERT INTO tables (name, capacity) VALUES ("R", 10);
INSERT INTO tables (name, capacity) VALUES ("S", 10);
INSERT INTO tables (name, capacity) VALUES ("T", 10);
