addSbtPlugin("com.lucidchart"   % "sbt-scalafmt-coursier" % "1.16")
addSbtPlugin("com.timushev.sbt" % "sbt-updates"           % "0.5.3")
addSbtPlugin("io.spray"         % "sbt-revolver"          % "0.9.1")
addSbtPlugin("org.scoverage"    % "sbt-scoverage"         % "1.9.3")
addSbtPlugin("org.scalameta"    % "sbt-scalafmt"          % "2.4.6")
